/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicaodontologica;

/**
 *
 * @author 85477044349
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCadastrarPaciente = new javax.swing.JMenuItem();
        mnuCadastrarDentista = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuAgendar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        mnuCadastrarPaciente.setText("Paciente");
        mnuCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarPacienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCadastrarPaciente);

        mnuCadastrarDentista.setText("Dentista");
        mnuCadastrarDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarDentistaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCadastrarDentista);
        jMenu1.add(jSeparator1);

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consulta");

        mnuAgendar.setText("Agendar");
        mnuAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAgendarActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAgendar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        //fechar o programa
        System.exit(0);
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarPacienteActionPerformed
        // 1 - Instanciar o objeto da Tela interna
        TelaCadastroPaciente telaInterna = new TelaCadastroPaciente();
        
        // 2 - Adcionar o objeto da tela ao jDesktopPane
        desktop.add(telaInterna);
        
        // 3 - Tornar visível a tela interna
        telaInterna.setVisible(true);
        
        //4 - Criar o X pra fechar a tela interna
        telaInterna.setClosable(true);
    }//GEN-LAST:event_mnuCadastrarPacienteActionPerformed

    private void mnuCadastrarDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarDentistaActionPerformed
          // 1 - Instanciar o objeto da Tela interna
        TelaCadastroDentista telaInterna = new TelaCadastroDentista();
        
        // 2 - Adcionar o objeto da tela ao jDesktopPane
        desktop.add(telaInterna);
        
        // 3 - Tornar visível a tela interna
        telaInterna.setVisible(true);
        
        //4 - Criar o X pra fechar a tela interna
        telaInterna.setClosable(true);
    }//GEN-LAST:event_mnuCadastrarDentistaActionPerformed

    private void mnuAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAgendarActionPerformed
         // 1 - Instanciar o objeto da Tela interna
        TelaAgendarConsulta telaInterna  = new TelaAgendarConsulta();
        
        // 2 - Adcionar o objeto da tela ao jDesktopPane
        desktop.add(telaInterna);
        
        // 3 - Tornar visível a tela interna
        telaInterna.setVisible(true);
        
        //4 - Criar o X pra fechar a tela interna
        telaInterna.setClosable(true);
    }//GEN-LAST:event_mnuAgendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnuAgendar;
    private javax.swing.JMenuItem mnuCadastrarDentista;
    private javax.swing.JMenuItem mnuCadastrarPaciente;
    private javax.swing.JMenuItem mnuSair;
    // End of variables declaration//GEN-END:variables
}
